// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file data.proto (package hakuraku, syntax proto2)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file data.proto.
 */
export const file_data: GenFile = /*@__PURE__*/
  fileDesc("CgpkYXRhLnByb3RvEghoYWt1cmFrdSL8AgoKVU1EYXRhYmFzZRIPCgd2ZXJzaW9uGAEgASgJEh4KBWNoYXJhGAIgAygLMg8uaGFrdXJha3UuQ2hhcmESHAoEY2FyZBgJIAMoCzIOLmhha3VyYWt1LkNhcmQSKwoMc3VwcG9ydF9jYXJkGAsgAygLMhUuaGFrdXJha3UuU3VwcG9ydENhcmQSLQoNcmFjZV9pbnN0YW5jZRgEIAMoCzIWLmhha3VyYWt1LlJhY2VJbnN0YW5jZRIeCgVza2lsbBgHIAMoCzIPLmhha3VyYWt1LlNraWxsEiUKCXRleHRfZGF0YRgMIAMoCzISLmhha3VyYWt1LlRleHREYXRhEkgKHHNpbmdsZV9tb2RlX3NraWxsX25lZWRfcG9pbnQYDSADKAsyIi5oYWt1cmFrdS5TaW5nbGVNb2RlU2tpbGxOZWVkUG9pbnQSMgoQc2luZ2xlX21vZGVfcmFuaxgOIAMoCzIYLmhha3VyYWt1LlNpbmdsZU1vZGVSYW5rIjQKBUNoYXJhEgoKAmlkGAEgASgFEgwKBG5hbWUYAiABKAkSEQoJY2FzdF9uYW1lGAMgASgJIiAKBENhcmQSCgoCaWQYASABKAUSDAoEbmFtZRgCIAEoCSI5CgtTdXBwb3J0Q2FyZBIKCgJpZBgBIAEoBRIMCgRuYW1lGAIgASgJEhAKCGNoYXJhX2lkGAMgASgFIq0BCgxSYWNlSW5zdGFuY2USCgoCaWQYASABKAUSDAoEbmFtZRgCIAEoCRIQCghkaXN0YW5jZRgDIAEoBRI2Cgtncm91bmRfdHlwZRgEIAEoDjIhLmhha3VyYWt1LlJhY2VJbnN0YW5jZS5Hcm91bmRUeXBlIjkKCkdyb3VuZFR5cGUSFwoTVU5LTk9XTl9HUk9VTkRfVFlQRRAAEggKBFRVUkYQARIICgRESVJUEAIiVgoFU2tpbGwSCgoCaWQYASABKAUSDAoEbmFtZRgCIAEoCRITCgtncmFkZV92YWx1ZRgDIAEoERIOCgZ0YWdfaWQYBCADKAkSDgoGcmFyaXR5GAUgASgFIkUKCFRleHREYXRhEgoKAmlkGAEgASgFEhAKCGNhdGVnb3J5GAIgASgFEg0KBWluZGV4GAMgASgFEgwKBHRleHQYBCABKAkiggEKGFNpbmdsZU1vZGVTa2lsbE5lZWRQb2ludBIKCgJpZBgBIAEoBRIYChBuZWVkX3NraWxsX3BvaW50GAIgASgFEhMKC3N0YXR1c190eXBlGAMgASgFEhQKDHN0YXR1c192YWx1ZRgEIAEoBRIVCg1zb2x2YWJsZV90eXBlGAUgASgFIkIKDlNpbmdsZU1vZGVSYW5rEgoKAmlkGAEgASgFEhEKCW1pbl92YWx1ZRgCIAEoBRIRCgltYXhfdmFsdWUYAyABKAU");

/**
 * @generated from message hakuraku.UMDatabase
 */
export type UMDatabase = Message<"hakuraku.UMDatabase"> & {
  /**
   * @generated from field: optional string version = 1;
   */
  version: string;

  /**
   * @generated from field: repeated hakuraku.Chara chara = 2;
   */
  chara: Chara[];

  /**
   * @generated from field: repeated hakuraku.Card card = 9;
   */
  card: Card[];

  /**
   * @generated from field: repeated hakuraku.SupportCard support_card = 11;
   */
  supportCard: SupportCard[];

  /**
   * @generated from field: repeated hakuraku.RaceInstance race_instance = 4;
   */
  raceInstance: RaceInstance[];

  /**
   * @generated from field: repeated hakuraku.Skill skill = 7;
   */
  skill: Skill[];

  /**
   * @generated from field: repeated hakuraku.TextData text_data = 12;
   */
  textData: TextData[];

  /**
   * @generated from field: repeated hakuraku.SingleModeSkillNeedPoint single_mode_skill_need_point = 13;
   */
  singleModeSkillNeedPoint: SingleModeSkillNeedPoint[];

  /**
   * @generated from field: repeated hakuraku.SingleModeRank single_mode_rank = 14;
   */
  singleModeRank: SingleModeRank[];
};

/**
 * Describes the message hakuraku.UMDatabase.
 * Use `create(UMDatabaseSchema)` to create a new message.
 */
export const UMDatabaseSchema: GenMessage<UMDatabase> = /*@__PURE__*/
  messageDesc(file_data, 0);

/**
 * @generated from message hakuraku.Chara
 */
export type Chara = Message<"hakuraku.Chara"> & {
  /**
   * @generated from field: optional int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: optional string name = 2;
   */
  name: string;

  /**
   * @generated from field: optional string cast_name = 3;
   */
  castName: string;
};

/**
 * Describes the message hakuraku.Chara.
 * Use `create(CharaSchema)` to create a new message.
 */
export const CharaSchema: GenMessage<Chara> = /*@__PURE__*/
  messageDesc(file_data, 1);

/**
 * @generated from message hakuraku.Card
 */
export type Card = Message<"hakuraku.Card"> & {
  /**
   * @generated from field: optional int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: optional string name = 2;
   */
  name: string;
};

/**
 * Describes the message hakuraku.Card.
 * Use `create(CardSchema)` to create a new message.
 */
export const CardSchema: GenMessage<Card> = /*@__PURE__*/
  messageDesc(file_data, 2);

/**
 * @generated from message hakuraku.SupportCard
 */
export type SupportCard = Message<"hakuraku.SupportCard"> & {
  /**
   * @generated from field: optional int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: optional string name = 2;
   */
  name: string;

  /**
   * @generated from field: optional int32 chara_id = 3;
   */
  charaId: number;
};

/**
 * Describes the message hakuraku.SupportCard.
 * Use `create(SupportCardSchema)` to create a new message.
 */
export const SupportCardSchema: GenMessage<SupportCard> = /*@__PURE__*/
  messageDesc(file_data, 3);

/**
 * @generated from message hakuraku.RaceInstance
 */
export type RaceInstance = Message<"hakuraku.RaceInstance"> & {
  /**
   * @generated from field: optional int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: optional string name = 2;
   */
  name: string;

  /**
   * @generated from field: optional int32 distance = 3;
   */
  distance: number;

  /**
   * @generated from field: optional hakuraku.RaceInstance.GroundType ground_type = 4;
   */
  groundType: RaceInstance_GroundType;
};

/**
 * Describes the message hakuraku.RaceInstance.
 * Use `create(RaceInstanceSchema)` to create a new message.
 */
export const RaceInstanceSchema: GenMessage<RaceInstance> = /*@__PURE__*/
  messageDesc(file_data, 4);

/**
 * @generated from enum hakuraku.RaceInstance.GroundType
 */
export enum RaceInstance_GroundType {
  /**
   * @generated from enum value: UNKNOWN_GROUND_TYPE = 0;
   */
  UNKNOWN_GROUND_TYPE = 0,

  /**
   * @generated from enum value: TURF = 1;
   */
  TURF = 1,

  /**
   * @generated from enum value: DIRT = 2;
   */
  DIRT = 2,
}

/**
 * Describes the enum hakuraku.RaceInstance.GroundType.
 */
export const RaceInstance_GroundTypeSchema: GenEnum<RaceInstance_GroundType> = /*@__PURE__*/
  enumDesc(file_data, 4, 0);

/**
 * @generated from message hakuraku.Skill
 */
export type Skill = Message<"hakuraku.Skill"> & {
  /**
   * @generated from field: optional int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: optional string name = 2;
   */
  name: string;

  /**
   * @generated from field: optional sint32 grade_value = 3;
   */
  gradeValue: number;

  /**
   * enum SingleModeDefine.SkillTag
   *    RunningStyleBegin = 100;
   *    Nige = 101;
   *    Senko = 102;
   *    Sashi = 103;
   *    Oikomi = 104;
   *    RunningStyleEnd = 199;
   *    DistanceBegin = 200;
   *    Short = 201;
   *    Mile = 202;
   *    Middle = 203;
   *    Long = 204;
   *    DistanceEnd = 299;
   *    SPEED = 401;
   *    STAMINA = 402;
   *    POWER = 403;
   *    GUTS = 404;
   *    WIZ = 405;
   *    DOWN = 406;
   *    SPECIAL = 407;
   *    GroundBegin = 500;
   *    Turf = 501;
   *    Dirt = 502;
   *    GroundEnd = 599;
   *    ScenarioBegin = 800;
   *    ScenarioEnd = 899;
   *
   * @generated from field: repeated string tag_id = 4;
   */
  tagId: string[];

  /**
   * @generated from field: optional int32 rarity = 5;
   */
  rarity: number;
};

/**
 * Describes the message hakuraku.Skill.
 * Use `create(SkillSchema)` to create a new message.
 */
export const SkillSchema: GenMessage<Skill> = /*@__PURE__*/
  messageDesc(file_data, 5);

/**
 * @generated from message hakuraku.TextData
 */
export type TextData = Message<"hakuraku.TextData"> & {
  /**
   * @generated from field: optional int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: optional int32 category = 2;
   */
  category: number;

  /**
   * @generated from field: optional int32 index = 3;
   */
  index: number;

  /**
   * @generated from field: optional string text = 4;
   */
  text: string;
};

/**
 * Describes the message hakuraku.TextData.
 * Use `create(TextDataSchema)` to create a new message.
 */
export const TextDataSchema: GenMessage<TextData> = /*@__PURE__*/
  messageDesc(file_data, 6);

/**
 * @generated from message hakuraku.SingleModeSkillNeedPoint
 */
export type SingleModeSkillNeedPoint = Message<"hakuraku.SingleModeSkillNeedPoint"> & {
  /**
   * @generated from field: optional int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: optional int32 need_skill_point = 2;
   */
  needSkillPoint: number;

  /**
   * @generated from field: optional int32 status_type = 3;
   */
  statusType: number;

  /**
   * @generated from field: optional int32 status_value = 4;
   */
  statusValue: number;

  /**
   * @generated from field: optional int32 solvable_type = 5;
   */
  solvableType: number;
};

/**
 * Describes the message hakuraku.SingleModeSkillNeedPoint.
 * Use `create(SingleModeSkillNeedPointSchema)` to create a new message.
 */
export const SingleModeSkillNeedPointSchema: GenMessage<SingleModeSkillNeedPoint> = /*@__PURE__*/
  messageDesc(file_data, 7);

/**
 * @generated from message hakuraku.SingleModeRank
 */
export type SingleModeRank = Message<"hakuraku.SingleModeRank"> & {
  /**
   * @generated from field: optional int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: optional int32 min_value = 2;
   */
  minValue: number;

  /**
   * @generated from field: optional int32 max_value = 3;
   */
  maxValue: number;
};

/**
 * Describes the message hakuraku.SingleModeRank.
 * Use `create(SingleModeRankSchema)` to create a new message.
 */
export const SingleModeRankSchema: GenMessage<SingleModeRank> = /*@__PURE__*/
  messageDesc(file_data, 8);

